server:
  port: 8081

spring:
  application:
    name: hmdp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: slf030621

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包


bloom:
  shop:
    name: shopBloomFilter
    expectedInsertions: 200000
    falsePositiveRate: 0.01
    pageSize: 2000

ai:
  vision:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    chat-path: /chat/completions
    api-key: sk-ff42bb6edbd84fc2911508949b05f507
    model: qwen3-vl-30b-a3b-instruct
    timeout-ms: 20000
  embed:
    endpoint: http://127.0.0.1:8000/embed
    expected-dim: 1024
    model: bge-m3
    normalize: true
    batch-size: 32
